module.exports = {
  scamWords: [
    "free nitro",
    "claim your prize",
    "click here",
    "limited time offer",
    "exclusive deal",
    "win a giveaway",
    "free steam key",
    "airdrop",
    "promo code",
    "event invite",
    "mrbeast giveaway",
    "nitro scam",
    "discord scam",
    "free discord",
    "discord giveaway",
    "steam giveaway",
    "free game",
    "@everyone",
    "@here",
    "leaks",
    "nsfw",
    "nudes",
    "onlyfans",
    "Message has been Redacted",
    "requires ID verification",
    "sensitive content",
    "verify your age group",
    "Teen age group",
    "age verification",
    "click the link below",
    "urgent action required",
    "account has been compromised",
    "verify your account",
    "update payment information",
    "congratulations you've won",
    "free gift card",
    "girl in vc",
    "showing her ass on cam",
    "Child Porn on this server",
    "join girl in cam",
    "she's squirting",
    "Check my profile vc",
    "join my server nudes",
    "DM for deal",
    "DM for deals",
    "See more",
    "Show more",
    "look at this wtf",
  ],
};